import type { ClassKey, SubclassKey } from '@rolling-dice-app/core'

/** 各主職業可選的子職業 key 列表（依官方來源順序） */
export const SUBCLASSES_BY_CLASS: Readonly<Record<ClassKey, readonly SubclassKey[]>> = {
  barbarian: [
    'berserker',
    'totemWarrior',
    'ancestralGuardian',
    'stormHerald',
    'zealot',
    'beast',
    'battlerager',
    'wildMagic',
    'giant',
    'juggernaut',
  ],
  bard: [
    'lore',
    'valor',
    'glamour',
    'swords',
    'whispers',
    'creation',
    'eloquence',
    'spirits',
    'tragedy',
  ],
  cleric: [
    'knowledge',
    'life',
    'light',
    'nature',
    'tempest',
    'trickery',
    'war',
    'forge',
    'grave',
    'arcana',
    'order',
    'peace',
    'twilight',
    'blood',
    'moon',
  ],
  druid: ['land', 'moon', 'dreams', 'shepherd', 'spores', 'stars', 'wildfire', 'blighted'],
  fighter: [
    'champion',
    'battleMaster',
    'eldritchKnight',
    'arcaneArcher',
    'cavalier',
    'samurai',
    'purpleDragonKnight',
    'echoKnight',
    'psiWarrior',
    'runeKnight',
  ],
  monk: [
    'openHand',
    'shadow',
    'fourElements',
    'drunkenMaster',
    'kensei',
    'sunSoul',
    'longDeath',
    'mercy',
    'astralSelf',
    'ascendantDragon',
    'cobaltSoul',
  ],
  paladin: [
    'devotion',
    'ancients',
    'vengeance',
    'crown',
    'conquest',
    'redemption',
    'glory',
    'watchers',
    'sea',
  ],
  ranger: [
    'hunter',
    'beastMaster',
    'gloomStalker',
    'horizonWalker',
    'monsterSlayer',
    'feyWanderer',
    'swarmkeeper',
    'drakewarden',
  ],
  rogue: [
    'thief',
    'assassin',
    'arcaneTrickster',
    'inquisitive',
    'mastermind',
    'scout',
    'swashbuckler',
    'phantom',
    'soulknife',
  ],
  sorcerer: [
    'draconicBloodline',
    'wildMagicSorcerer',
    'divineSoul',
    'shadowMagic',
    'stormSorcery',
    'aberrantMind',
    'clockworkSoul',
    'lunarSorcery',
    'runeChild',
  ],
  warlock: [
    'archfey',
    'fiend',
    'celestial',
    'hexblade',
    'undying',
    'greatOldOne',
    'fathomless',
    'genie',
    'undead',
  ],
  wizard: [
    'abjuration',
    'conjuration',
    'divination',
    'enchantment',
    'evocation',
    'illusion',
    'necromancy',
    'transmutation',
    'warMagic',
    'bladesinging',
    'chronurgyMagic',
    'graviturgyMagic',
    'bloodMagic',
    'scribes',
  ],
  artificer: ['alchemist', 'armorer', 'artillerist', 'battleSmith'],
}
