import type { ProfessionKey, SubprofessionKey } from '@rolling-dice-app/types'

/**
 * 子職業中文 label，依主職業分組以避免子職業 key 同名衝突（如 cleric 與 druid 皆有 moon）。
 * 查詢方式：SUBPROFESSION_CONFIG[profession][subprofessionKey]
 */
export const SUBPROFESSION_CONFIG: Readonly<
  Record<ProfessionKey, Readonly<Partial<Record<SubprofessionKey, string>>>>
> = {
  barbarian: {
    berserker: '狂戰士道途',
    totemWarrior: '圖騰戰士道途',
    ancestralGuardian: '先祖守衛道途',
    stormHerald: '風暴先驅道途',
    zealot: '狂熱者道途',
    beast: '野獸之路道途',
    battlerager: '戰狂道途',
    wildMagic: '狂野魔法道途',
    giant: '巨人道途',
    Juggernaut: '撼山者道途',
  },
  bard: {
    lore: '知識學院',
    valor: '勇氣學院',
    glamour: '迷惑學院',
    swords: '劍舞學院',
    whispers: '低語學院',
    creation: '創造學院',
    eloquence: '雄辯學院',
    spirits: '靈魂學院',
    tragedy: '悲劇學院',
  },
  cleric: {
    knowledge: '知識領域',
    life: '生命領域',
    light: '光明領域',
    nature: '自然領域',
    tempest: '暴風領域',
    trickery: '詭術領域',
    war: '戰爭領域',
    forge: '鍛造領域',
    grave: '墳墓領域',
    arcana: '奧秘領域',
    order: '秩序領域',
    peace: '和平領域',
    twilight: '薄暮領域',
    blood: '鮮血領域',
    moon: '月亮領域',
  },
  druid: {
    land: '大地結社',
    moon: '月亮結社',
    dreams: '夢境結社',
    shepherd: '牧人結社',
    spores: '孢子結社',
    stars: '星辰結社',
    wildfire: '野火結社',
    blighted: '荒蕪結社',
  },
  fighter: {
    champion: '勇士',
    battleMaster: '戰鬥大師',
    eldritchKnight: '魔能騎士',
    arcaneArcher: '魔射手',
    cavalier: '騎兵',
    samurai: '武士',
    purpleDragonKnight: '紫龍騎士',
    echoKnight: '回音騎士',
    psiWarrior: '靈能武士',
    runeKnight: '符文騎士',
  },
  monk: {
    openHand: '散打宗',
    shadow: '暗影宗',
    fourElements: '四象宗',
    drunkenMaster: '醉拳宗',
    kensei: '劍聖宗',
    sunSoul: '日魂宗',
    longDeath: '永亡宗',
    mercy: '命流宗',
    astralSelf: '星我宗',
    ascendantDragon: '神龍宗',
    cobaltSoul: '鈷魂宗',
  },
  paladin: {
    devotion: '奉獻之誓',
    ancients: '遠古之誓',
    vengeance: '復仇之誓',
    crown: '王冠之誓',
    conquest: '征服之誓',
    redemption: '救贖之誓',
    glory: '榮耀之誓',
    watchers: '守望之誓',
    sea: '遠洋之誓',
  },
  ranger: {
    hunter: '獵人',
    beastMaster: '獸王',
    gloomStalker: '幽域追蹤者',
    horizonWalker: '境界行者',
    monsterSlayer: '怪物殺手',
    feyWanderer: '妖精漫遊者',
    swarmkeeper: '集群守衛',
    drakewarden: '龍獸守衛',
  },
  rogue: {
    thief: '竊賊',
    assassin: '刺客',
    arcaneTrickster: '詭術師',
    inquisitive: '審訊者',
    mastermind: '策士',
    scout: '斥候',
    swashbuckler: '風流劍客',
    phantom: '鬼魅',
    soulknife: '魂刃',
  },
  sorcerer: {
    draconicBloodline: '龍族血脈',
    wildMagicSorcerer: '狂野魔法',
    divineSoul: '神聖之魂',
    shadowMagic: '幽影魔法',
    stormSorcery: '暴風術法',
    aberrantMind: '畸變心智',
    clockworkSoul: '時械之魂',
    lunarSorcery: '月亮術法',
    runeChild: '符文之子',
  },
  warlock: {
    archfey: '至高妖精',
    fiend: '邪魔宗主',
    celestial: '天界宗主',
    hexblade: '咒劍士',
    undying: '不朽者',
    greatOldOne: '舊日支配者',
    fathomless: '深海意志',
    genie: '巨靈宗主',
    undead: '不死宗主',
  },
  wizard: {
    abjuration: '防護學派',
    conjuration: '咒法學派',
    divination: '預言學派',
    enchantment: '惑控學派',
    evocation: '塑能學派',
    illusion: '幻象學派',
    necromancy: '死靈學派',
    transmutation: '變化學派',
    warMagic: '戰爭魔法',
    bladesinging: '劍歌',
    chronurgyMagic: '時間魔法',
    graviturgyMagic: '重力魔法',
    bloodMagic: '血魔法',
    scribes: '書士會',
  },
  artificer: {
    alchemist: '鍊金師',
    armorer: '裝甲師',
    artillerist: '魔砲師',
    battleSmith: '戰地匠師',
  },
}

/** 各主職業可選的子職業 key 列表（依官方來源順序） */
export const SUBPROFESSION_BY_PROFESSION: Readonly<
  Record<ProfessionKey, readonly SubprofessionKey[]>
> = {
  barbarian: [
    'berserker',
    'totemWarrior',
    'ancestralGuardian',
    'stormHerald',
    'zealot',
    'beast',
    'battlerager',
    'wildMagic',
    'giant',
    'Juggernaut',
  ],
  bard: [
    'lore',
    'valor',
    'glamour',
    'swords',
    'whispers',
    'creation',
    'eloquence',
    'spirits',
    'tragedy',
  ],
  cleric: [
    'knowledge',
    'life',
    'light',
    'nature',
    'tempest',
    'trickery',
    'war',
    'forge',
    'grave',
    'arcana',
    'order',
    'peace',
    'twilight',
    'blood',
    'moon',
  ],
  druid: ['land', 'moon', 'dreams', 'shepherd', 'spores', 'stars', 'wildfire', 'blighted'],
  fighter: [
    'champion',
    'battleMaster',
    'eldritchKnight',
    'arcaneArcher',
    'cavalier',
    'samurai',
    'purpleDragonKnight',
    'echoKnight',
    'psiWarrior',
    'runeKnight',
  ],
  monk: [
    'openHand',
    'shadow',
    'fourElements',
    'drunkenMaster',
    'kensei',
    'sunSoul',
    'longDeath',
    'mercy',
    'astralSelf',
    'ascendantDragon',
    'cobaltSoul',
  ],
  paladin: [
    'devotion',
    'ancients',
    'vengeance',
    'crown',
    'conquest',
    'redemption',
    'glory',
    'watchers',
    'sea',
  ],
  ranger: [
    'hunter',
    'beastMaster',
    'gloomStalker',
    'horizonWalker',
    'monsterSlayer',
    'feyWanderer',
    'swarmkeeper',
    'drakewarden',
  ],
  rogue: [
    'thief',
    'assassin',
    'arcaneTrickster',
    'inquisitive',
    'mastermind',
    'scout',
    'swashbuckler',
    'phantom',
    'soulknife',
  ],
  sorcerer: [
    'draconicBloodline',
    'wildMagicSorcerer',
    'divineSoul',
    'shadowMagic',
    'stormSorcery',
    'aberrantMind',
    'clockworkSoul',
    'lunarSorcery',
    'runeChild',
  ],
  warlock: [
    'archfey',
    'fiend',
    'celestial',
    'hexblade',
    'undying',
    'greatOldOne',
    'fathomless',
    'genie',
    'undead',
  ],
  wizard: [
    'abjuration',
    'conjuration',
    'divination',
    'enchantment',
    'evocation',
    'illusion',
    'necromancy',
    'transmutation',
    'warMagic',
    'bladesinging',
    'chronurgyMagic',
    'graviturgyMagic',
    'bloodMagic',
    'scribes',
  ],
  artificer: ['alchemist', 'armorer', 'artillerist', 'battleSmith'],
}
