import { randomUUID } from 'node:crypto'
import type {
  DmSessionContainerCreateBody,
  DmSessionContainerDTO,
  DmSessionLogCreateBody,
  DmSessionLogDTO,
  DmSessionMemberInput,
} from '@rolling-dice-app/core'
import { seedPost } from './api'

/**
 * Seed a DM session container (the "campaign" that holds session logs) and its
 * logs through the real endpoints, so the create contract stays the single
 * source of truth.
 *
 * Both bodies take the same write-shape member entry (`DmSessionMemberInput`:
 * `{ id, playerName, characterShareId }`), where `characterShareId` must be a
 * *shared* character's id — see `shareCharacter`. The container carries the
 * standing roster; each log carries who actually attended that session.
 *
 * Note for battlefield flows: a battlefield's `sessionId` is a **session log
 * id**, not a container id (`listSessionOptions` in
 * `backend/src/repositories/battlefields.ts` projects `dmSessionLogs.id`).
 */
export async function seedDmSessionContainer(
  sessionId: string,
  body: DmSessionContainerCreateBody,
): Promise<DmSessionContainerDTO> {
  return seedPost<DmSessionContainerDTO>('/dm-session-containers', sessionId, body)
}

export async function seedDmSessionLog(
  sessionId: string,
  containerId: string,
  body: DmSessionLogCreateBody,
): Promise<DmSessionLogDTO> {
  return seedPost<DmSessionLogDTO>(
    `/dm-session-containers/${encodeURIComponent(containerId)}/session-logs`,
    sessionId,
    body,
  )
}

/** A roster/attendance entry; the inline `id` is client-generated by contract. */
export function memberInput(
  playerName: string,
  characterShareId: string | null = null,
): DmSessionMemberInput {
  return { id: randomUUID(), playerName, characterShareId }
}
